### ISSUE TITLE
Should we be supporting other key types with DID Key?

### ISSUE THREAD

**Issue by kdenhartog** [w3c-ccg/did-method-key#3]
I think there's some advantages with DID:key that could be useful around supporting additional key types. Right now it's very specific to `ed25519` keys but in the future I could see it supporting Secp256k1, RSA, and NIST curves as well. Is this something that the authors/implementors are open to exploring or do we intentionally want to restrict this functionality for simplicity?

One of the main questions that would come up for me is how should be deriving the key agreement keys if we're supporting additional types. For example, I believe mixing RSA based DH and signing is insecure, but there are algorithms that can be used with the ECC pairings that are shown to be secure.

See here for resource: https://eprint.iacr.org/2011/615

**Comment by OR13** [comment]
Cross linking: https://github.com/w3c-ccg/did-method-key/issues/1

**Comment by dmitrizagidulin** [comment]
I think the current design would support other key types, since it uses Multiformat / Multi-encoding in its urls. 
So, although the current examples and usage is with ed25519, the pattern listed in the spec is:

did:key:<multi-encoded multiformat representation of the public key>.
 (which happens to use base58 encoded ed25519 public keys - but that’s fully self describing, not hardcoded)

**Comment by dmitrizagidulin** [comment]
So the procedure to express other types of keys is:

1. Find the `multicodec` representation for your key type. For example, the registration for  secp256k1 keys is pending over at https://github.com/multiformats/multicodec/pull/160.
2. Encode the raw public key bytes using that multicodec value.
3. Pick a character encoding (I suggest base58-btc), and convert it to a character string using Multibase.
4. Prepend `did:key:` to that string, and there you have it!

**Comment by OR13** [comment]
Adding a PNG Dump of the previous discussion... 
![screencapture-github-w3c-ccg-did-method-key-issues-1-2020-03-04-14_22_57](https://user-images.githubusercontent.com/8295856/75920022-3177f480-5e24-11ea-8e53-c938cd3384ea.png)

**Comment by OR13** [comment]
@expede what multicodec value did you use for did:key RSA2048, there are no values in this table: https://github.com/multiformats/multicodec/blob/master/table.csv for RSA....

I suggest we close this issue, as its being discussed elsewhere... and the TL;DR; is... other key types ARE supported :)

**Comment by kdenhartog** [comment]
Agreed, this is supported (although not fully documented in the spec yet) and implementation can be inferred. Closing this issue.
