### ISSUE TITLE
Elliptic curve point compression

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/did-method-key#32]
The public keys in the test vectors for Secp256k1 are in compressed form (33 bytes), but for P-256 they are uncompressed (64 bytes, untagged). For Ed25519 they are compressed (32 bytes).

- Should P-256 use compressed form instead? The smaller size in a URI may be desirable, and this would be consistent with the use of Secp256k1 and Ed25519.
- Should `did:key` allow either form - compressed or uncompressed - for these key types? Or only a single form is allowed? Or either form allowed but one is preferred?

**Comment by OR13** [comment]
imo, did-key method spec should probably stick to compressed only... the main reason the NIST curves are uncompressed is that they are commonly represented uncompressed... I did the first version of them and now @troyronda and SecureKey have support for them as well... 

I am not sure how hard it would be to convert did key for nist curves to compressed, but if we can, we should IMO.

**Comment by msporny** [comment]
> * Should P-256 use compressed form instead? The smaller size in a URI may be desirable, and this would be consistent with the use of Secp256k1 and Ed25519.

Yes, because the smaller size URI is a desirable feature.

> * Should `did:key` allow either form - compressed or uncompressed - for these key types? Or only a single form is allowed? Or either form allowed but one is preferred?

Let's just stick to compressed form, I don't see a need to support both.

**Comment by dlongley** [comment]
Some links on P-256 compressed form:

https://tools.ietf.org/html/rfc5480
https://tools.ietf.org/id/draft-jivsov-ecc-compact-05.html
https://stackoverflow.com/a/30431547/399274

**Comment by OR13** [comment]
One issue we have is that we only support did key variants that have some JWK representation, so we won't implement support for this until we can easily convert back and forth.... because we like interoperability with off the shelf JOSE libraries.

I will need to take a look at bi-directional transformations to be sure its possible to support.

**Comment by bshambaugh** [comment]
+1 Orie. I'm presently contemplating building a function that takes both the compressed and uncompressed versions and produces a JWK representation.

**Comment by oed** [comment]
You can use a library such as `elliptic` to convert keys back and forth between compressed and uncompressed. Although, it's a big dependency that would be nice to avoid if possible!

```js
let ec = new require('elliptic').ec('p256')
undefined
> ec.genKeyPair().getPublic(true, 'hex')
'03413029cb9a5a4a0b087a9b8a060116d0d32bb22d14aebf7778215744811bb6ce'
> pub = ec.keyFromPublic('03413029cb9a5a4a0b087a9b8a060116d0d32bb22d14aebf7778215744811bb6ce', 'hex').getPublic(false, 'hex')
'04413029cb9a5a4a0b087a9b8a060116d0d32bb22d14aebf7778215744811bb6ce40780d7bb9e2e068879f443e05b21b8fc0b62c9c811008064d988856077e35e7'
```

**Comment by bshambaugh** [comment]
I have some code over here that supports raw public keys, compressed public keys, and uncompressed public keys for P-256. https://github.com/ceramicnetwork/js-ceramic/pull/1418

**Comment by OR13** [comment]
Anyone on this thread want to take a stab at updating the test vectors in this repo to use the compressed from for P-256, P-384, P-521?

just edits to the JSON files.

**Comment by bshambaugh** [comment]
I will look at it.

I can use (or slightly modify) this to create test vectors (given the raw or uncompressed public key input):
https://github.com/bshambaugh/key-did-provider-secp256r1/blob/main/src/index.ts

By changing about 3 lines of code I believe that this could be written for P-384 and P-521.
https://github.com/bshambaugh/js-ceramic/blob/develop/packages/key-did-resolver/src/secp256r1.ts

**Comment by clehner** [comment]
I get the following for the P-256 one:
```
did:key:zDnaerx9CtbPJ1q36T5Ln5wYt3MQYeGRG5ehnPAmxcf5mDZpv
```

**Comment by bshambaugh** [comment]
did:key:zDnaeUKTWUXc1HDpGfKbEK31nKLN19yX5aunFd7VK1CUMeyJu
did:key:zDnaerx9CtbPJ1q36T5Ln5wYt3MQYeGRG5ehnPAmxcf5mDZpv

Yes. I had one that looked similar in my tests.

**Comment by bshambaugh** [comment]
Okay. I started a pull request: https://github.com/w3c-ccg/did-method-key/pull/36

**Comment by bshambaugh** [comment]
> I get the following for the P-256 one:
> 
> ```
> did:key:zDnaerx9CtbPJ1q36T5Ln5wYt3MQYeGRG5ehnPAmxcf5mDZpv
> ```

Awesome. Thanks. I am got the same thing.

**Comment by OR13** [comment]
I think this is done, recommend closing.

**Comment by oed** [comment]
👍 
Note that multicodec table also have been updated to explicitly state that keys should be compressed: https://github.com/multiformats/multicodec/blob/master/table.csv#L136-L138

**Comment by bshambaugh** [comment]
I remember that P-521 had some problems. I recall writing some code for
P-256 and P-384 NIST curves with a generic wrapper for it. P-521 was
different, IIRC. I haven't touched this code in a while, but I thought I
should get back to that a few days ago.  I could open up a PR  when I get
to it, or whatever works.

-Brent

**Comment by OR13** [comment]
@bshambaugh please consider raising a separate issue for that if you find anything wrong with P-521...
