### ISSUE TITLE
DID Example 2 doesn't match with the example URL in 3.1 Create

### ISSUE THREAD

**Issue by sunday18** [w3c-ccg/did-method-key#50]
hi

In DID:Key spec (https://w3c-ccg.github.io/did-method-key/) Section 3.1 Create, it mentions a did:key example did:key did:key:z6MkpTHR8VNsBxYAAWHut2Geadd9jSwuBV8xRoAnwWsdvktH. However, Example 2 shows a DID document for another DID, did:key:z6MkicdicToW5HbxPP7zZV1H7RHvXgRMhoujWAF2n5WQkdd2. It is very confusing for readers. Please help to rectify this issue in the spec. 

Thanks.

**Comment by msporny** [comment]
Good catch! Thank you.

Fixed in a8b5d22f4be4aa0de78e3cab23fb6135492fad60.
