### ISSUE TITLE
Move to CCG

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/did-method-key#6]
https://github.com/w3c-ccg/did-method-key

I'm eager to propose changes to did-method-key, but worried about having 2 repos open / duplicate issues / PRs... I would love to get this into the CCG asap :)

**Comment by dmitrizagidulin** [comment]
@OR13 it would be great to ask the CCG admins to delete the existing https://github.com/w3c-ccg/did-method-key repo, and then we can just transfer this one (that way, all the issues and PRs etc will be transferred).

**Comment by OR13** [comment]
I deleted it. Please transfer away!

**Comment by dmitrizagidulin** [comment]
Transferred! Closing this issue.
