### ISSUE TITLE
Key Type

### ISSUE THREAD

**Issue by David-Chadwick** [w3c-ccg/did-method-key#7]
I would like to suggest that did:key supports different key types. Two key types have already been identified:
- jwt keys
- dlt keys

the structure would therefore become 
```
did:key:<type>:<type specific key encoding
```
For the jwt type I would like to suggest the following encoding
```
did:key:jwt:<base 64 encoded public key>
```
Note that the algorithm id is not needed in the jwt key encoding because this is already included in the JWT header in its own alg parameter

For the dlt type this would follow the encoding specified in the draft by @msporny i.e. the key and algorithm are encoded together using base58 encoding

**Comment by OR13** [comment]
This issue has been moved around a bit, but its safe to comment on again :)

Linking the discussion from the JS implementation as its relevant to the did method spec: https://github.com/digitalbazaar/did-method-key-js/issues/8

**Comment by OR13** [comment]
@David-Chadwick @msporny @dlongley We need to address this issue, its been open for ages...

First, the current spec relies on multiformats for encoding public key bytes...@David-Chadwick wants to use a self attested JWT of a JWK instead... something like:

`did:key:JWT`

Where JWT is some kind of self signed JWK.

There are a couple problems with this approach.

1. There is no canonical representation for JWKs (multiple identifiers for the same public key bytes).
2. There is no need to provide an assertion (the public key bytes would be enough, you don't need a signature).

Based on these points, I would recommend the following:

#### Option 1

We close this issue, and @David-Chadwick creates a new DID Method for what he wants to do.... I would recommend creating a spec that generates canonical JWKs using JCS and then just do something like:

`did:jwk:base64url(cannonical(JWK))`

#### Option 2

We agree extend DID Key with something like option 1....

I an in favor of just doing option 1, somewhere else... especially after spending as much time with canonical JSON in sidetree as I have.... asking for a did key as a JWK seems like for of a job for resolver options than a did param or an entire alternate encoding for a did method.

**Comment by David-Chadwick** [comment]
Hi Orie

thanks very much for coming back on this.

On 02/08/2020 19:28, Orie Steele wrote:
>
> @David-Chadwick <https://github.com/David-Chadwick> @msporny 
> <https://github.com/msporny> @dlongley <https://github.com/dlongley> 
> We need to address this issue, its been open for ages...
>
> First, the current spec relies on multiformats for encoding public key 
> bytes...@David-Chadwick <https://github.com/David-Chadwick> wants to 
> use a self attested JWT of a JWK instead... something like:
>
> |did:key:JWT|
>
> Where JWT is some kind of self signed JWK.
>
Not quite. The JWT final value is simply the base 64 encoding of the 
public key according to RFC 7517. It is very similar to what you have 
proposed elsewhere in which you use separate JSON properties for each of 
the public key arguments (alg, n and e (for RSA), or x and y (for EC)). 
In my proposal, this JSON structure of the key value pairs is base64 
encoded to make one value for the last component of the did key. When 
you base 64 decode it you get back the separate key value pairs in the 
JSON structure (as in your model).

> There are a couple problems with this approach.
>
>  1. There is no canonical representation for JWKs (multiple
>     identifiers for the same public key bytes).
>
This is irrelevant in my model as the public keys are not 
multi-directional, but only uni-directional i.e. shared between the 
holder and one other party, as per Kim Cameron's Laws of Identity. The 
holder has different public keys for all other parties. So providing the 
other party get all the key value pairs by base64 decoding the value, it 
does not matter in what order they were put into the encoding (x, y or 
y, x for example). You never re-encode it. Perhaps you are making the 
same mistake that X.509 made in 1988 when it invented the distinguished 
encoding rules (DER) because it was wrongly believed that you needed a 
canonical format for the BER signature. The misbelief then was that when 
a signature is chained between parties, each one would decode it then 
re-encode it before passing it on. Wrong. You keep the bytes you receive 
and pass them on exactly as you get them (after decoding to validate the 
signature). DER was never needed.


>  1. There is no need to provide an assertion (the public key bytes
>     would be enough, you don't need a signature).
>
correct. I have never asserted this. I am not sure where this misbelief 
came from.
>
> Based on these points, I would recommend the following:
>
>
>         Option 1
>
> We close this issue, and @David-Chadwick 
> <https://github.com/David-Chadwick> creates a new DID Method for what 
> he wants to do.... I would recommend creating a spec that generates 
> canonical JWKs using JCS and then just do something like:
>
> |did:jwk:base64url(cannonical(JWK))|
>
|actually it would be did:jwk:(base64encoding of public key parameters 
according to RFC 7517)|
>
>
>         Option 2
>
> We agree extend DID Key with something like option 1....
>
> I an in favor of just doing option 1, somewhere else... especially 
> after spending as much time with canonical JSON in sidetree as I have
>
That's a pity, because it is not necessary in my opinion

Kind regards

David

**Comment by msporny** [comment]
> I an in favor of just doing option 1

I am as well, after having looked into this a bit adding a JWK representation pulls in a kitchen sink of JOSE dependencies into did:key (which we're trying to avoid). I had played around with the idea of making did:key:jwk optional, as in, a did:key implementation doesn't have to support it, but if it does... then it does what you propose above. That could be an acceptable compromise, or, as @OR13 suggests, we just do did:jwk elsewhere due to the complexity (and we could easily have mappings between the multicodec did:key and JOSE did:jwk.

I've been holding back wrt. saying this until we had a did:key:jwk  implementation under our belts and could then understand the fullness of the concern I outline above. We've only spent a day here and there exploring it... that none of our customer systems have needed JWK yet is telling (at least, internally).

In any case, +1 to @OR13's suggestion. We like the direction that the JwsSignature2020 (and family) stuff is going in, so if we can do the same for did:jwk, that'd be ideal. Then we'd have a clear line between "the way things have been done" and "a potentially better way to do things".

**Comment by OR13** [comment]
@David-Chadwick I suggest you link to a spec for `did:jwk` / what you are currently doing, and we close this issue.

if you are indeed not worried about multiple ids for the same key type, that seems like a fundamental incompatibility with the mental model of did:key... however.. its entirely equivalent to what I did with `did:meme`... you can have multiple dids (memes) for the same public key bytes.... there are privacy advantages to that approach which you should be free to explore in a separate spec :)

**Comment by OR13** [comment]
I am closing this issue, I would happily review a PR to add an information reference to whatever comes of it down the road to the did key method spec.
